
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS student;
CREATE TABLE student (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32));

DROP TABLE IF EXISTS courses;
CREATE TABLE courses (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, course VARCHAR (32), category_id INTEGER);

DROP TABLE IF EXISTS categoryes;
CREATE TABLE categoryes (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, category VARCHAR (32));

--DROP TABLE IF EXISTS cat_course; -- связка курс-категория
--CREATE TABLE cat_course (id integer PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, category_id INTEGER, course_id INTEGER);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
